site_name: Waya Documentation
repo_url: https://github.com/Luna-devv/waya-docs
repo_name: Luna-devv/waya-docs
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: assets/waya.jpg
  features:
    - navigation.tabs
  palette:
    - scheme: slate
      primary: purple
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
    - scheme: default 
      primary: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
extra:
  homepage: https://waya.one
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/Luni_sia
    - icon: fontawesome/brands/github 
      link: https://github.com/Luna-devv
  analytics:
    provider: google
    property: G-XQXN71MSCL
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde