site_name: Waya Documentation
repo_url: https://github.com/Luna-devv/waya-docs
repo_name: Luna-devv/waya-docs
theme:
  name: material
  palette:
    - scheme: slate
      primary: purple
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
    - scheme: default 
      primary: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/Luni_sia
    - icon: fontawesome/brands/github 
      link: https://github.com/Luna-devv
